// ---------------------------------------------------------------------------
// fir_coeffs.vh -- AUTO-GENERATED by scripts/gen_coeffs.py. Do not edit by hand.
//
// 16-tap symmetric low-pass FIR, Hamming-windowed sinc.
//   fs = 1.0 MHz, fc = 140 kHz, Q1.15 fixed point.
//   Coefficient sum = 32768 (unity DC gain).
//   Verified response: -0.23 dB @ 50 kHz, -2.04 dB @ 100 kHz,
//                      -54.17 dB @ 400 kHz,
//                      worst -54.12 dB over [300 kHz, fs/2].
//
// Packing: FIR_COEFFS[16*i +: 16] is tap i (tap 0 in the least-significant
// 16 bits). Each tap is a signed 16-bit Q1.15 value.
// ---------------------------------------------------------------------------
localparam signed [255:0] FIR_COEFFS = 256'h0022FF9AFE4DFD63006D0A1A17E0222D222D17E00A1A006DFD63FE4DFF9A0022;
