#!/usr/bin/env python3
"""Windowed-sinc coefficient generator for the 16-tap FIR low-pass filter.

Design:
    sample rate fs = 1 MHz, Hamming-windowed sinc, cutoff fc = 140 kHz,
    16 symmetric taps, quantized to Q1.15.

The 16-tap / 1-MHz combination was chosen by grid search so that a plain
windowed-sinc design meets the stopband target (about -48 dB or better at
400 kHz and everywhere above 300 kHz) while keeping about -2 dB at 100 kHz
and about -0.25 dB loss at 50 kHz.

Outputs:
    rtl/fir_coeffs.vh  -- packed Verilog localparam with the 16 Q1.15 taps.

Quantization keeps the filter symmetric and forces the tap sum to exactly
32768 (2^15), i.e. unity DC gain in Q1.15.
"""

import os
import numpy as np

FS = 1_000_000.0   # sample rate, Hz
N = 16             # taps
FC = 140_000.0     # cutoff frequency, Hz
Q = 15             # Q1.15
UNITY = 1 << Q     # 32768


def design_float():
    """Hamming-windowed sinc, normalized to unity DC gain."""
    n = np.arange(N)
    m = (N - 1) / 2.0
    h = np.sinc(2.0 * (FC / FS) * (n - m))
    h = h * np.hamming(N)
    return h / h.sum()


def quantize(h):
    """Quantize the 8 unique taps of the symmetric filter to Q1.15.

    The residual needed to hit an exact sum of 2^15 is absorbed by the
    largest-magnitude tap pair, so symmetry is preserved exactly.
    """
    unique = h[: N // 2]
    q = np.round(unique * UNITY).astype(np.int64)
    residual = (UNITY // 2) - int(q.sum())   # sum of 8 unique taps must be 2^14
    q[int(np.argmax(np.abs(unique)))] += residual
    full = np.concatenate([q, q[::-1]]).astype(np.int64)
    assert full.sum() == UNITY, f"tap sum {full.sum()} != {UNITY}"
    assert np.all(full == full[::-1]), "symmetry broken"
    assert np.all(np.abs(full) <= 32768)
    return full


def resp_db(h_float, freqs):
    """Frequency response in dB of tap vector h at given frequencies."""
    n = np.arange(len(h_float))
    out = []
    for f in freqs:
        H = np.sum(h_float * np.exp(-2j * np.pi * f / FS * n))
        out.append(20.0 * np.log10(abs(H) + 1e-18))
    return out


def main():
    h = design_float()
    q = quantize(h)
    hq = q.astype(float) / UNITY  # quantized taps as floats for response check

    r50, r100, r400 = resp_db(hq, [50_000.0, 100_000.0, 400_000.0])
    grid = np.linspace(300_000.0, FS / 2, 2001)
    worst_stop = max(resp_db(hq, grid))

    print(f"design: {N}-tap Hamming-windowed sinc, fc={FC/1e3:.0f} kHz, fs={FS/1e6:.1f} MHz")
    print(f"quantized tap sum = {q.sum()} (target {UNITY})")
    print(f"symmetric: {bool(np.all(q == q[::-1]))}")
    print(f"|H( 50 kHz)| = {r50:+.2f} dB   (target approx -0.25 dB)")
    print(f"|H(100 kHz)| = {r100:+.2f} dB   (target approx -2 dB)")
    print(f"|H(400 kHz)| = {r400:+.2f} dB   (target <= -48 dB)")
    print(f"worst |H| over [300 kHz, fs/2] = {worst_stop:+.2f} dB   (target <= -48 dB)")

    ok = (-0.6 <= r50 <= 0.0 and -3.0 <= r100 <= -1.0
          and r400 <= -48.0 and worst_stop <= -48.0)
    print("SPEC CHECK:", "PASS" if ok else "FAIL")
    if not ok:
        raise SystemExit(1)

    taps_hex = "".join(f"{int(t) & 0xFFFF:04X}" for t in q[::-1])  # tap15..tap0, MSB first
    vh = f"""// ---------------------------------------------------------------------------
// fir_coeffs.vh -- AUTO-GENERATED by scripts/gen_coeffs.py. Do not edit by hand.
//
// 16-tap symmetric low-pass FIR, Hamming-windowed sinc.
//   fs = {FS/1e6:.1f} MHz, fc = {FC/1e3:.0f} kHz, Q1.15 fixed point.
//   Coefficient sum = {q.sum()} (unity DC gain).
//   Verified response: {r50:+.2f} dB @ 50 kHz, {r100:+.2f} dB @ 100 kHz,
//                      {r400:+.2f} dB @ 400 kHz,
//                      worst {worst_stop:+.2f} dB over [300 kHz, fs/2].
//
// Packing: FIR_COEFFS[16*i +: 16] is tap i (tap 0 in the least-significant
// 16 bits). Each tap is a signed 16-bit Q1.15 value.
// ---------------------------------------------------------------------------
localparam signed [255:0] FIR_COEFFS = 256'h{taps_hex};
"""
    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "..", "rtl", "fir_coeffs.vh")
    with open(out_path, "w") as f:
        f.write(vh)
    print(f"wrote {os.path.normpath(out_path)}")
    print("taps (Q1.15 decimal):", ", ".join(str(int(t)) for t in q))


if __name__ == "__main__":
    main()
